create table if not exists public.ai_species_references (
  id integer generated by default as identity primary key,
  name text not null,
  location_type smallint not null references public.location_types(id),
  scientific_name text,
  identification_notes text[] not null default '{}',
  source_title text not null,
  source_url text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_species_references_name_location_type_key unique (name, location_type),
  constraint ai_species_references_location_type_check check (location_type in (1, 2)),
  constraint ai_species_references_name_not_blank check (
    char_length(btrim(name)) > 0
  ),
  constraint ai_species_references_source_title_not_blank check (
    char_length(btrim(source_title)) > 0
  ),
  constraint ai_species_references_source_url_not_blank check (
    char_length(btrim(source_url)) > 0
  )
);

alter table public.ai_species_references enable row level security;

drop trigger if exists set_ai_species_references_updated_at
on public.ai_species_references;
create trigger set_ai_species_references_updated_at
before update on public.ai_species_references
for each row
execute function public.set_updated_at();

drop policy if exists "Anyone can view AI species references"
on public.ai_species_references;
create policy "Anyone can view AI species references"
on public.ai_species_references
for select
to anon, authenticated
using (is_active);

insert into public.ai_species_references (
  location_type,
  name,
  scientific_name,
  identification_notes,
  source_title,
  source_url
)
values
  (
    2,
    '강도다리',
    'Platichthys stellatus',
    array[
      '등지느러미와 뒷지느러미에 반복적이고 일정한 검은 줄무늬가 보이면 강도다리를 우선 후보로 본다.',
      '도다리와 동의어로 처리하지 말고, 지느러미 줄무늬가 보이지 않을 때만 도다리를 별도 후보로 둔다.'
    ],
    '국립생물자원관 한반도의 생물다양성',
    'https://species.nibr.go.kr'
  ),
  (
    2,
    '문치가자미',
    'Pseudopleuronectes yokohamae',
    array[
      '몸이 납작하고 한쪽으로 눈이 몰린 가자미류이며, 도다리로 통칭되는 경우가 많아 가자미류 후보와 함께 비교한다.',
      '강도다리처럼 지느러미에 일정한 검은 줄무늬가 반복되는 특징이 뚜렷하면 문치가자미보다 강도다리를 우선한다.'
    ],
    '국립수산과학원 수산자원정보',
    'https://www.nifs.go.kr'
  ),
  (
    2,
    '참가자미',
    null,
    array[
      '가자미류는 사진 각도에 따라 서로 혼동되기 쉬우므로 몸 형태, 체색 반점, 지느러미 무늬를 함께 비교한다.'
    ],
    '국립수산과학원 수산자원정보',
    'https://www.nifs.go.kr'
  ),
  (2, '용가자미', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '기름가자미', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '가자미', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '서대', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '박대', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (
    2,
    '보리멸',
    null,
    array['길고 가는 은백색 몸과 모래 바닥 어종에 가까운 체형이면 보리멸을 후보로 본다.'],
    '국립수산과학원 수산자원정보',
    'https://www.nifs.go.kr'
  ),
  (
    2,
    '성대',
    null,
    array['큰 가슴지느러미가 날개처럼 펼쳐지고 머리 부분이 단단해 보이면 성대를 후보로 본다.'],
    '국립수산과학원 수산자원정보',
    'https://www.nifs.go.kr'
  ),
  (2, '양태', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (
    2,
    '쏨뱅이',
    null,
    array['암초 주변에서 잡히는 붉거나 갈색 얼룩 체색, 큰 머리와 가시가 두드러지면 쏨뱅이를 후보로 본다.'],
    '국립수산과학원 수산자원정보',
    'https://www.nifs.go.kr'
  ),
  (2, '쑤기미', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '아귀', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (
    2,
    '노래미',
    null,
    array['쥐노래미와 비슷한 체형이므로 몸의 무늬, 색, 머리 형태가 애매하면 두 후보를 함께 반환한다.'],
    '국립수산과학원 수산자원정보',
    'https://www.nifs.go.kr'
  ),
  (2, '불볼락', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '열기', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '개볼락', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '망상어', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '자리돔', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '벤자리', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '독가시치', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '혹돔', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '능성어', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (
    2,
    '전갱이',
    null,
    array['고등어보다 몸이 더 납작하고 측선 비늘이 뚜렷한 은색 회유성 어종이면 전갱이를 후보로 본다.'],
    '국립수산과학원 수산자원정보',
    'https://www.nifs.go.kr'
  ),
  (
    2,
    '학꽁치',
    null,
    array['가늘고 긴 몸과 길게 돌출된 아래턱이 뚜렷하면 학꽁치를 우선 후보로 본다.'],
    '국립수산과학원 수산자원정보',
    'https://www.nifs.go.kr'
  ),
  (
    2,
    '숭어',
    null,
    array['원통형에 가까운 은색 몸, 큰 비늘, 두툼한 입 주변이 보이면 숭어를 후보로 본다.'],
    '국립수산과학원 수산자원정보',
    'https://www.nifs.go.kr'
  ),
  (
    2,
    '전어',
    null,
    array['몸이 납작한 은색이고 배 쪽이 칼날처럼 보이는 청어류 체형이면 전어를 후보로 본다.'],
    '국립수산과학원 수산자원정보',
    'https://www.nifs.go.kr'
  ),
  (2, '가다랑어', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '만새기', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '꼬치고기', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (
    2,
    '민어',
    null,
    array['조기류보다 큰 체급, 길쭉한 몸, 은회색 체색이면 민어를 후보로 본다.'],
    '국립수산과학원 수산자원정보',
    'https://www.nifs.go.kr'
  ),
  (
    2,
    '백조기',
    null,
    array['참조기, 보구치, 부세와 혼동되기 쉬우므로 체색의 노란 기운, 입과 머리 형태, 체고를 함께 비교한다.'],
    '국립수산과학원 수산자원정보',
    'https://www.nifs.go.kr'
  ),
  (2, '보구치', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (
    2,
    '참조기',
    null,
    array['조기류는 서로 비슷하므로 참조기, 백조기, 보구치, 부세를 함께 후보로 검토하고 확신이 낮으면 confidence를 낮춘다.'],
    '국립수산과학원 수산자원정보',
    'https://www.nifs.go.kr'
  ),
  (2, '부세', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '수조기', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (
    2,
    '대구',
    null,
    array['아래턱 수염과 큰 머리, 길쭉한 몸이 보이면 대구를 후보로 본다.'],
    '국립수산과학원 수산자원정보',
    'https://www.nifs.go.kr'
  ),
  (
    2,
    '도루묵',
    null,
    array['동해권에서 자주 보이는 길쭉한 몸과 큰 눈, 반투명한 느낌의 체색이면 도루묵을 후보로 본다.'],
    '국립수산과학원 수산자원정보',
    'https://www.nifs.go.kr'
  ),
  (2, '임연수어', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '청어', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '꽁치', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '물메기', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '꼼치', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (
    2,
    '갯장어',
    null,
    array['붕장어보다 길고 날카로운 입과 이빨이 두드러지면 갯장어를 후보로 본다.'],
    '국립수산과학원 수산자원정보',
    'https://www.nifs.go.kr'
  ),
  (2, '먹장어', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '한치', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (
    2,
    '살오징어',
    null,
    array['오징어류 중 몸통이 길고 지느러미가 몸통 뒤쪽에 삼각형으로 붙어 보이면 살오징어를 후보로 본다.'],
    '국립수산과학원 수산자원정보',
    'https://www.nifs.go.kr'
  ),
  (
    2,
    '낙지',
    null,
    array['팔이 길고 몸통이 작으며 문어류보다 전체 크기가 작아 보이면 낙지를 후보로 본다.'],
    '국립수산과학원 수산자원정보',
    'https://www.nifs.go.kr'
  ),
  (2, '참문어', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '대문어', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '꽃게', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '대게', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr'),
  (2, '홍게', null, '{}', '국립수산과학원 수산자원정보', 'https://www.nifs.go.kr')
on conflict (name, location_type) do update
set
  scientific_name = excluded.scientific_name,
  identification_notes = excluded.identification_notes,
  source_title = excluded.source_title,
  source_url = excluded.source_url,
  is_active = true;

delete from public.fish_species
where location_type = 2
  and name in (
    '강도다리',
    '문치가자미',
    '참가자미',
    '용가자미',
    '기름가자미',
    '가자미',
    '서대',
    '박대',
    '보리멸',
    '성대',
    '양태',
    '쏨뱅이',
    '쑤기미',
    '아귀',
    '노래미',
    '불볼락',
    '열기',
    '개볼락',
    '망상어',
    '자리돔',
    '벤자리',
    '독가시치',
    '혹돔',
    '능성어',
    '전갱이',
    '학꽁치',
    '숭어',
    '전어',
    '가다랑어',
    '만새기',
    '꼬치고기',
    '민어',
    '백조기',
    '보구치',
    '참조기',
    '부세',
    '수조기',
    '대구',
    '도루묵',
    '임연수어',
    '청어',
    '꽁치',
    '물메기',
    '꼼치',
    '갯장어',
    '먹장어',
    '한치',
    '살오징어',
    '낙지',
    '참문어',
    '대문어',
    '꽃게',
    '대게',
    '홍게'
  );
