create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text,
  avatar_url text,
  signup_provider text check (
    signup_provider in ('apple', 'kakao', 'google')
  ),
  status text not null default 'active' check (
    status in ('active', 'blocked', 'deleted')
  ),
  role text not null default 'user' check (
    role in ('user', 'admin')
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile"
on public.profiles
for select
to authenticated
using ((select auth.uid()) = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles
for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  provider text;
begin
  provider := nullif(new.raw_app_meta_data ->> 'provider', '');

  if provider not in ('apple', 'kakao', 'google') then
    provider := null;
  end if;

  insert into public.profiles (id, nickname, avatar_url, signup_provider)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data ->> 'nickname',
      new.raw_user_meta_data ->> 'name',
      new.raw_user_meta_data ->> 'full_name'
    ),
    coalesce(
      new.raw_user_meta_data ->> 'avatar_url',
      new.raw_user_meta_data ->> 'picture'
    ),
    provider
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

create table if not exists public.location_types (
  id smallint primary key,
  name text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.location_types is
  'Fishing location type reference data.';

alter table public.location_types enable row level security;

drop trigger if exists set_location_types_updated_at on public.location_types;
create trigger set_location_types_updated_at
before update on public.location_types
for each row
execute function public.set_updated_at();

drop policy if exists "Anyone can view location types" on public.location_types;
create policy "Anyone can view location types"
on public.location_types
for select
to anon, authenticated
using (true);

insert into public.location_types (id, name)
values
  (1, '민물'),
  (2, '바다')
on conflict (id) do update
set name = excluded.name;

create table if not exists public.fish_species (
  id integer generated by default as identity primary key,
  name text not null,
  location_type smallint not null references public.location_types(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint fish_species_name_location_type_key unique (name, location_type),
  constraint fish_species_location_type_check check (location_type in (1, 2)),
  constraint fish_species_name_not_blank check (
    char_length(btrim(name)) > 0
  )
);

comment on table public.fish_species is
  'Fish species reference data. location_type: 1=freshwater, 2=saltwater.';

comment on column public.fish_species.location_type is
  '1=freshwater, 2=saltwater';

alter table public.fish_species enable row level security;

drop trigger if exists set_fish_species_updated_at on public.fish_species;
create trigger set_fish_species_updated_at
before update on public.fish_species
for each row
execute function public.set_updated_at();

drop policy if exists "Anyone can view fish species" on public.fish_species;
create policy "Anyone can view fish species"
on public.fish_species
for select
to anon, authenticated
using (true);

insert into public.fish_species (id, location_type, name)
values
  (1, 2, '우럭'),
  (2, 2, '광어'),
  (3, 2, '참돔'),
  (4, 2, '감성돔'),
  (5, 2, '돌돔'),
  (6, 2, '벵에돔'),
  (7, 2, '농어'),
  (8, 2, '방어'),
  (9, 2, '부시리'),
  (10, 2, '고등어'),
  (11, 2, '갈치'),
  (12, 2, '볼락'),
  (13, 2, '쥐노래미'),
  (14, 2, '무늬오징어'),
  (15, 2, '쭈꾸미'),
  (16, 2, '갑오징어'),
  (17, 2, '문어'),
  (18, 2, '삼치'),
  (19, 2, '도다리'),
  (20, 2, '붕장어'),
  (21, 1, '붕어'),
  (22, 1, '잉어'),
  (23, 1, '배스'),
  (24, 1, '블루길'),
  (25, 1, '가물치'),
  (26, 1, '메기'),
  (27, 1, '쏘가리'),
  (28, 1, '꺽지'),
  (29, 1, '피라미'),
  (30, 1, '강준치'),
  (31, 1, '끄리'),
  (32, 1, '송어'),
  (33, 1, '산천어'),
  (34, 1, '빙어'),
  (35, 1, '장어')
on conflict (id) do update
set
  location_type = excluded.location_type,
  name = excluded.name;

select setval(
  pg_get_serial_sequence('public.fish_species', 'id'),
  greatest((select max(id) from public.fish_species), 1),
  true
);
